Test for stow right before stowing

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -30,19 +30,6 @@ set -e
 
 source $DOTFILES_ROOT_ABS/shell_functions.sh
 
-function check_requirements {
-  local err=0
-
-  if ! stow -V &>/dev/null
-  then
-    fail "GNU stow not found in PATH"
-    err=1
-  fi
-
-  [ $err -ne 0 ] && exit 1
-  return 0
-}
-
 function run_installers() {
   # Start with Homebrew as installers might depend on brew installed software
   homebrew_installer="${DOTFILES_ROOT_ABS}/homebrew/install.$(uname -s).sh"
@@ -57,12 +44,17 @@ function run_installers() {
   done
 }
 
-check_requirements
-
 prompt_confirm "Shall the installers run (y/n)?" && (info "Running installers..." ; run_installers)
 
 echo ""
 info "Installing dotfiles..."
+
+if ! stow -V &>/dev/null
+then
+  fail "GNU stow not found in PATH"
+  exit 1
+fi
+
 for stowable in $stowables
 do
   stow -R --ignore install.*sh $stowable && success $stowable || warning $stowable
